spring.application.name=atvpontuada

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/atvpontuada
spring.datasource.username=root
spring.datasource.password=